- name: Configuring nginx
  import_tasks: "nginx.yml"

- name: ensure "{{userName}}" user exists
  user:
    name: "{{userName}}"
    group: www-data
    generate_ssh_key: True
    system: False


- name: "Add README.md to {{userName}}'s home dir"
  template:
    src: README.md
    dest: ~{{userName}}/README.md

- name: ensure {{userName}} user can manage own systemd unit files
  command: loginctl enable-linger {{userName}}

- name: Make sure default home folders exist.
  become: True
  become_user: "{{userName}}"
  file:
    path: "~{{userName}}/{{item}}"
    recurse: True
    state: directory
    mode: 0750
  with_items: 
    - www
    - logs
    - fallback
    - .config/systemd/user/

- name: Make publickey available at <yoursite>/~{{userName}}/id_rsa.pub
  file:
    src: '~{{userName}}/.ssh/id_rsa.pub'
    dest: '~{{userName}}/www/id_rsa.pub'
    state: hard

- name: Register publickey
  command: cat '~{{userName}}/.ssh/id_rsa.pub'
  register: pubkey

- name: Print publickey
  debug: msg="{{pubkey.stdout}}"

- name: Pull latest git
  become: True
  become_user: "{{userName}}"
  git:
    accept_hostkey: True
    force: True
    repo: "{{source}}"
    version: "{{branch}}" #Defaults to `master`
    dest: "~{{userName}}/app"
  when: source != None

- name: Ensure {{userName}} postgresql database exists
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{userName}}"

- name: Ensure database user exists
  become: true
  become_user: postgres
  postgresql_user:
    db: "{{userName}}"
    name: "{{userName}}"
    password: "{{lookup('password', 'data/{{userName}}_postgresPassword.txt length=32')}}"
    priv: "CONNECT/ALL"

- name: Running {{type}} specific setup
  include_tasks: "app/{{type}}.yml"
  when: type != None

- name: Run misc commands
  command: "{{item}}"
  args:
    chdir: ~{{userName}}/
  become: True
  become_user: "{{userName}}"
  with_items: "{{commands}}"

- name: create systemd services for uwsgi app
  become: True
  become_user: "{{userName}}"
  template:
    src: "{{item}}"
    dest: ~{{userName}}/.config/systemd/user/{{item}}
  with_items:
    - app.service
    - socket.service

- name: Register uid of "{{userName}}"
  command: id -u {{userName}}
  register: uid

- name: Enable systemd services for uwsgi app
  become: True
  become_user: "{{userName}}"

  with_items:
    - app.service
#    - socket.service
  systemd:
    daemon_reload: True
    name: "{{item}}"
    enabled: True
    user: True
    state: restarted
  environment:
    XDG_RUNTIME_DIR: /run/user/{{uid.stdout}}
