- name: Insert/update home folder serving block into {{default_nginx_site}}
  notify:
     - restart nginx
  blockinfile:
    path: "{{default_nginx_site}}"
    marker: "	# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: "^server {"
    ########
    # BEWAARE THE TABS
    # :set listchars=tab:␉·
    # :set list
    ########
    block: |
      	location ~ ^/~(.+?)(/.*)?$ {
      		root /home/$1/www;
      		try_files $2 @uwsgiApp;
      		error_page 404 /404.html
      	}
      	location @uwsgiApp {
      		uwsgi_pass unix:///home/$1/app.socket;
      		include uwsgi_params;
      	}
