- name: Insert/update home folder serving block into {{default_nginx_site}}
  notify:
     - restart nginx
  blockinfile:
    path: "{{default_nginx_site}}"
    marker: "	# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: "^server {"
    ########
    # BEWAARE THE TABS
    # :set listchars=tab:␉·
    # :set list
    ########
    block: "{{ lookup('file', 'templates/nginx_homeDirs.conf') }}"
- name: Set up sub domains
  template:
    src: templates/nginx_domain.conf
    dest: /etc/nginx/sites-available/{{name}}.conf
    owner: root
    group: root
    mode: 0644
  notify:
     - restart nginx
  when: domains != False
