- name: Create a virtualenv for django app using requirements.txt
  become: True
  become_user: "{{userName}}"
  pip: 
    virtualenv: ~{{userName}}/virtualenv/
    virtualenv_python: "{{python}}"
    requirements: ~{{userName}}/app/requirements.txt

- name: Make sure psycopg2 is installed
  become: True
  become_user: "{{userName}}"
  pip: 
    virtualenv: ~{{userName}}/virtualenv/
    virtualenv_python: "{{python}}"
    name: psycopg2

- name: Move {{django_settings}} to {{django_settings| dirname}}orig_{{django_settings| basename}}
  copy:
    remote_src: True
    src: ~{{userName}}/app/{{django_settings}}
    dest: ~{{userName}}/app/{{django_settings| dirname}}/orig_{{django_settings| basename}}

- name: Template out our new django settings
  template:
    src: django_settings.py
    dest: ~{{userName}}/app/{{django_settings}}

- name: Create uwsgi.ini for django app
  template:
    src: uwsgi-types/django.ini
    dest: ~{{userName}}/uwsgi.ini
  become: True
  become_user: "{{userName}}"

- name: Run django management commands
  become: True
  become_user: "{{userName}}"
  command: ~{{userName}}/virtualenv/bin/python ~{{userName}}/app/{{item}}
  with_items:
    - manage.py migrate
    - manage.py collectstatic --noinput

# TODO: add support for celery and django-channels workers as systemd user units.
